/* التعصب والتسامح — FANATICISM & TOLERANCE — app.js v1.0 */
/* Based on "Al-Taassub wal-Tasamuh" by Sheikh Mohammed al-Ghazali (1917-1996) */

const T = {
  ar: {
    appTitle: 'التعصب والتسامح',
    splashSub: 'بين المسيحية والإسلام',
    splashHint: 'اضغط للتخطي',
    sacredRef: 'سورة الحجرات ٤٩: ١٣',
    tabHome: 'الرئيسية', tabCards: 'البطاقات', tabTolerance: 'التسامح',
    tabHabits: 'العادات', tabQuiz: 'اختبار', tabAbout: 'الكتاب',
    cardsTitle: 'بطاقات التسامح',
    cardsDesc: '٢٠ بطاقة في التسامح الإسلامي والتعايش بين الأديان',
    toleranceTitle: 'نماذج التسامح',
    toleranceDesc: 'نماذج تاريخية في التسامح الإسلامي مقارنة بالتعصب',
    habitsTitle: 'عاداتي اليومية', habitsDesc: 'عادات التسامح والتعايش',
    quizTitle: 'اختبر نفسك', quizDesc: 'هل أنت متسامح حقاً؟',
    helpTitle: '❓ مساعدة', duaPanelTitle: '🤲 أدعية',
    resetBtn: 'إعادة تعيين اليوم', submitQuiz: 'اعرف النتيجة',
    dailyLabel: '✨ درس اليوم', quizAgain: 'أعد الاختبار',
    yes: 'نعم', no: 'لا', sometimes: 'أحياناً', share: 'مشاركة',
    searchPlaceholder: 'ابحث في البطاقات...', streakMsg: 'يوم متتالي!',
    allDone: 'أحسنت! أكملت جميع العادات!',
    splashFeatures: ['٢٠ بطاقة في التسامح الإسلامي','نماذج تاريخية في التعايش','عادات يومية مع تتبع مستمر','اختبار ذاتي + أدعية'],
  },
  en: {
    appTitle: 'Fanaticism & Tolerance',
    splashSub: 'Between Christianity and Islam',
    splashHint: 'tap to skip',
    sacredRef: 'Surah Al-Hujurat 49:13',
    tabHome: 'Home', tabCards: 'Cards', tabTolerance: 'Tolerance',
    tabHabits: 'Habits', tabQuiz: 'Quiz', tabAbout: 'Book',
    cardsTitle: 'Tolerance Cards',
    cardsDesc: '20 cards on Islamic tolerance and interfaith coexistence',
    toleranceTitle: 'Models of Tolerance',
    toleranceDesc: 'Historical models of Islamic tolerance compared to fanaticism',
    habitsTitle: 'My Daily Habits', habitsDesc: 'Habits of tolerance and coexistence',
    quizTitle: 'Test Yourself', quizDesc: 'Are you truly tolerant?',
    helpTitle: '❓ Help', duaPanelTitle: '🤲 Duas',
    resetBtn: 'Reset Today', submitQuiz: 'See Results',
    dailyLabel: '✨ Today\'s Lesson', quizAgain: 'Retake Quiz',
    yes: 'Yes', no: 'No', sometimes: 'Sometimes', share: 'Share',
    searchPlaceholder: 'Search cards...', streakMsg: 'day streak!',
    allDone: 'Well done! All habits completed!',
    splashFeatures: ['20 cards on Islamic tolerance','Historical models of coexistence','Daily habits with streak tracking','Self-quiz + duas'],
  },
  fr: {
    appTitle: 'Fanatisme et Tolerance',
    splashSub: 'Entre Christianisme et Islam',
    splashHint: 'appuyez pour passer',
    sacredRef: 'Sourate Al-Hujurat 49:13',
    tabHome: 'Accueil', tabCards: 'Cartes', tabTolerance: 'Tolerance',
    tabHabits: 'Habitudes', tabQuiz: 'Quiz', tabAbout: 'Livre',
    cardsTitle: 'Cartes de Tolerance',
    cardsDesc: '20 cartes sur la tolerance islamique et la coexistence interreligieuse',
    toleranceTitle: 'Modeles de Tolerance',
    toleranceDesc: 'Modeles historiques de tolerance islamique compares au fanatisme',
    habitsTitle: 'Mes Habitudes', habitsDesc: 'Habitudes de tolerance et coexistence',
    quizTitle: 'Testez-Vous', quizDesc: 'Etes-vous vraiment tolerant ?',
    helpTitle: '❓ Aide', duaPanelTitle: '🤲 Duas',
    resetBtn: 'Reinitialiser', submitQuiz: 'Voir les Resultats',
    dailyLabel: '✨ Lecon du Jour', quizAgain: 'Refaire le Quiz',
    yes: 'Oui', no: 'Non', sometimes: 'Parfois', share: 'Partager',
    searchPlaceholder: 'Rechercher...', streakMsg: 'jours consecutifs !',
    allDone: 'Bravo ! Toutes les habitudes accomplies !',
    splashFeatures: ['20 cartes sur la tolerance islamique','Modeles historiques de coexistence','Habitudes quotidiennes avec suivi','Quiz + duas'],
  }
};

const CARDS = [
  {id:1,emoji:'🕊️',ar:{title:'لا إكراه في الدين',desc:'الإسلام أعلن حرية العقيدة بنص قرآني صريح. هذا المبدأ سبق كل إعلانات حقوق الإنسان بقرون.',quran:'لَا إِكْرَاهَ فِي الدِّينِ قَد تَّبَيَّنَ الرُّشْدُ مِنَ الْغَيِّ',quranRef:'البقرة ٢: ٢٥٦',action:'تعامل اليوم مع الجميع باحترام بغض النظر عن معتقداتهم'},en:{title:'No Compulsion in Religion',desc:'Islam declared freedom of belief through explicit Quranic text. This principle preceded all human rights declarations by centuries.',quran:'There is no compulsion in religion — the right path is distinct from error',quranRef:'Al-Baqarah 2:256',action:'Treat everyone today with respect regardless of their beliefs'},fr:{title:'Pas de Contrainte en Religion',desc:'L\'Islam a declare la liberte de croyance par un texte coranique explicite. Ce principe a precede toutes les declarations des droits de l\'homme de plusieurs siecles.',quran:'Nulle contrainte en religion — le chemin droit se distingue de l\'erreur',quranRef:'Al-Baqarah 2:256',action:'Traitez tout le monde aujourd\'hui avec respect quelles que soient ses croyances'}},
  {id:2,emoji:'🤝',ar:{title:'التعارف لا التصادم',desc:'الله خلق الناس شعوباً وقبائل ليتعارفوا لا ليتصادموا. التنوع البشري حكمة إلهية.',quran:'يَا أَيُّهَا النَّاسُ إِنَّا خَلَقْنَاكُم مِّن ذَكَرٍ وَأُنثَىٰ وَجَعَلْنَاكُمْ شُعُوبًا وَقَبَائِلَ لِتَعَارَفُوا',quranRef:'الحجرات ٤٩: ١٣',action:'تعرف اليوم على ثقافة مختلفة عن ثقافتك'},en:{title:'Knowing, Not Clashing',desc:'God created people as nations and tribes to know one another, not to clash. Human diversity is divine wisdom.',quran:'O people, We created you from male and female and made you nations and tribes to know one another',quranRef:'Al-Hujurat 49:13',action:'Learn about a different culture today'},fr:{title:'Se Connaitre, Pas Se Heurter',desc:'Dieu a cree les gens en nations et tribus pour qu\'ils se connaissent, pas pour qu\'ils se heurtent. La diversite humaine est une sagesse divine.',quran:'O gens, Nous vous avons crees d\'un male et d\'une femelle et Nous vous avons faits en nations et tribus pour que vous vous connaissiez',quranRef:'Al-Hujurat 49:13',action:'Decouvrez une culture differente aujourd\'hui'}},
  {id:3,emoji:'🏰',ar:{title:'العهدة العمرية',desc:'عندما فتح عمر بن الخطاب القدس أعطى أهلها الأمان على كنائسهم وصلبانهم. نموذج فريد في التسامح.',quran:'لَكُمْ دِينُكُمْ وَلِيَ دِينِ',quranRef:'الكافرون ١٠٩: ٦',action:'اقرأ عن العهدة العمرية وكيف حمت حقوق غير المسلمين'},en:{title:'The Covenant of Umar',desc:'When Umar conquered Jerusalem, he guaranteed safety for churches and crosses. A unique model of tolerance.',quran:'For you is your religion and for me is mine',quranRef:'Al-Kafirun 109:6',action:'Read about the Covenant of Umar and how it protected non-Muslim rights'},fr:{title:'Le Pacte d\'Omar',desc:'Quand Omar a conquis Jerusalem, il a garanti la securite des eglises et des croix. Un modele unique de tolerance.',quran:'A vous votre religion et a moi la mienne',quranRef:'Al-Kafirun 109:6',action:'Lisez sur le pacte d\'Omar et la protection des droits des non-musulmans'}},
  {id:4,emoji:'⚔️',ar:{title:'الحروب الصليبية: السياق',desc:'الحروب الصليبية كانت حروباً سياسية بغطاء ديني. المسلمون دافعوا عن أرضهم ولم يبدأوا بالعدوان.',quran:'أُذِنَ لِلَّذِينَ يُقَاتَلُونَ بِأَنَّهُمْ ظُلِمُوا',quranRef:'الحج ٢٢: ٣٩',action:'ابحث عن الحقائق التاريخية للحروب الصليبية من مصادر محايدة'},en:{title:'The Crusades: Context',desc:'The Crusades were political wars under religious cover. Muslims defended their land and did not initiate aggression.',quran:'Permission is given to those who fight because they have been wronged',quranRef:'Al-Hajj 22:39',action:'Research the historical facts of the Crusades from neutral sources'},fr:{title:'Les Croisades : Le Contexte',desc:'Les Croisades etaient des guerres politiques sous couvert religieux. Les musulmans ont defendu leur terre et n\'ont pas initie l\'agression.',quran:'Permission est donnee a ceux qui combattent car ils ont ete leses',quranRef:'Al-Hajj 22:39',action:'Recherchez les faits historiques des Croisades a partir de sources neutres'}},
  {id:5,emoji:'📜',ar:{title:'حقوق أهل الذمة',desc:'الإسلام كفل لغير المسلمين في الدولة الإسلامية حقوقهم الكاملة في العبادة والتملك والقضاء.',quran:'لَّا يَنْهَاكُمُ اللَّهُ عَنِ الَّذِينَ لَمْ يُقَاتِلُوكُمْ فِي الدِّينِ أَن تَبَرُّوهُمْ وَتُقْسِطُوا إِلَيْهِمْ',quranRef:'الممتحنة ٦٠: ٨',action:'اقرأ عن حقوق أهل الذمة في الحضارة الإسلامية'},en:{title:'Rights of Non-Muslims',desc:'Islam guaranteed non-Muslims in Islamic states their full rights in worship, ownership, and judiciary.',quran:'God does not forbid you from being kind and just to those who do not fight you in religion',quranRef:'Al-Mumtahanah 60:8',action:'Read about the rights of non-Muslims in Islamic civilization'},fr:{title:'Droits des Non-Musulmans',desc:'L\'Islam a garanti aux non-musulmans dans les Etats islamiques leurs pleins droits de culte, de propriete et de justice.',quran:'Dieu ne vous interdit pas d\'etre bons et equitables envers ceux qui ne vous combattent pas en religion',quranRef:'Al-Mumtahanah 60:8',action:'Lisez sur les droits des non-musulmans dans la civilisation islamique'}},
  {id:6,emoji:'🌍',ar:{title:'الأندلس نموذج التعايش',desc:'في الأندلس عاش المسلمون واليهود والمسيحيون معاً في سلام لقرون. كانت منارة للعلم والتسامح.',quran:'وَلَوْ شَاءَ رَبُّكَ لَجَعَلَ النَّاسَ أُمَّةً وَاحِدَةً',quranRef:'هود ١١: ١١٨',action:'تعرف على قصة التعايش في الأندلس'},en:{title:'Al-Andalus: A Model of Coexistence',desc:'In Al-Andalus, Muslims, Jews, and Christians lived together in peace for centuries. It was a beacon of knowledge and tolerance.',quran:'Had your Lord willed, He would have made the people one nation',quranRef:'Hud 11:118',action:'Learn about the story of coexistence in Al-Andalus'},fr:{title:'Al-Andalus : Un Modele de Coexistence',desc:'En Al-Andalus, musulmans, juifs et chretiens ont vecu ensemble en paix pendant des siecles. C\'etait un phare de savoir et de tolerance.',quran:'Si ton Seigneur avait voulu, Il aurait fait des gens une seule communaute',quranRef:'Hud 11:118',action:'Decouvrez l\'histoire de la coexistence en Al-Andalus'}},
  {id:7,emoji:'💬',ar:{title:'الحوار بين الأديان',desc:'القرآن دعا للحوار مع أهل الكتاب والبحث عن القواسم المشتركة بدلاً من التصادم.',quran:'قُلْ يَا أَهْلَ الْكِتَابِ تَعَالَوْا إِلَىٰ كَلِمَةٍ سَوَاءٍ بَيْنَنَا وَبَيْنَكُمْ',quranRef:'آل عمران ٣: ٦٤',action:'ابحث عن قاسم مشترك مع شخص مختلف عنك في المعتقد'},en:{title:'Interfaith Dialogue',desc:'The Quran called for dialogue with the People of the Book and searching for common ground rather than conflict.',quran:'Say: O People of the Book, come to a word common between us and you',quranRef:'Aal Imran 3:64',action:'Find common ground with someone of a different belief today'},fr:{title:'Le Dialogue Interreligieux',desc:'Le Coran a appele au dialogue avec les Gens du Livre et a la recherche d\'un terrain commun plutot que le conflit.',quran:'Dis : O Gens du Livre, venez a une parole commune entre nous et vous',quranRef:'Aal Imran 3:64',action:'Trouvez un terrain commun avec une personne de croyance differente'}},
  {id:8,emoji:'⚖️',ar:{title:'العدل مع المخالف',desc:'القرآن أمر بالعدل حتى مع الأعداء. العدل أقرب للتقوى من التعصب.',quran:'وَلَا يَجْرِمَنَّكُمْ شَنَآنُ قَوْمٍ عَلَىٰ أَلَّا تَعْدِلُوا',quranRef:'المائدة ٥: ٨',action:'كن عادلاً في حكمك على الآخرين اليوم'},en:{title:'Justice with Opponents',desc:'The Quran commanded justice even with enemies. Justice is closer to piety than bigotry.',quran:'And let not the hatred of a people prevent you from being just',quranRef:'Al-Maidah 5:8',action:'Be fair in your judgment of others today'},fr:{title:'La Justice Envers les Opposants',desc:'Le Coran a ordonne la justice meme envers les ennemis. La justice est plus proche de la piete que le fanatisme.',quran:'Et que la haine d\'un peuple ne vous incite pas a etre injustes',quranRef:'Al-Maidah 5:8',action:'Soyez equitable dans votre jugement des autres aujourd\'hui'}},
  {id:9,emoji:'🕌',ar:{title:'حماية دور العبادة',desc:'الإسلام أمر بحماية الكنائس والمعابد والمساجد. تدمير دور العبادة حرام في الإسلام.',quran:'وَلَوْلَا دَفْعُ اللَّهِ النَّاسَ بَعْضَهُم بِبَعْضٍ لَّهُدِّمَتْ صَوَامِعُ وَبِيَعٌ وَصَلَوَاتٌ وَمَسَاجِدُ',quranRef:'الحج ٢٢: ٤٠',action:'تعرف على كيف حمى المسلمون الكنائس عبر التاريخ'},en:{title:'Protecting Houses of Worship',desc:'Islam commanded the protection of churches, temples, and mosques. Destroying places of worship is forbidden in Islam.',quran:'Were it not that God checks people by means of others, monasteries, churches, synagogues, and mosques would have been demolished',quranRef:'Al-Hajj 22:40',action:'Learn how Muslims protected churches throughout history'},fr:{title:'Proteger les Lieux de Culte',desc:'L\'Islam a ordonne la protection des eglises, temples et mosquees. Detruire les lieux de culte est interdit en Islam.',quran:'Si Dieu ne repoussait pas les gens les uns par les autres, les monasteres, eglises, synagogues et mosquees seraient demolis',quranRef:'Al-Hajj 22:40',action:'Decouvrez comment les musulmans ont protege les eglises a travers l\'histoire'}},
  {id:10,emoji:'📖',ar:{title:'احترام الأنبياء جميعاً',desc:'المسلم يؤمن بجميع الأنبياء ويحترمهم. عيسى وموسى عليهما السلام أنبياء معظمون في الإسلام.',quran:'لَا نُفَرِّقُ بَيْنَ أَحَدٍ مِّن رُّسُلِهِ',quranRef:'البقرة ٢: ٢٨٥',action:'اقرأ قصة نبي مشترك بين الأديان الثلاثة'},en:{title:'Respecting All Prophets',desc:'Muslims believe in and respect all prophets. Jesus and Moses are honored prophets in Islam.',quran:'We make no distinction between any of His messengers',quranRef:'Al-Baqarah 2:285',action:'Read about a prophet shared by the three religions'},fr:{title:'Respecter Tous les Prophetes',desc:'Les musulmans croient en tous les prophetes et les respectent. Jesus et Moise sont des prophetes honores en Islam.',quran:'Nous ne faisons pas de distinction entre Ses messagers',quranRef:'Al-Baqarah 2:285',action:'Lisez sur un prophete commun aux trois religions'}},
  {id:11,emoji:'❤️',ar:{title:'البر والإحسان لغير المسلمين',desc:'البر والإحسان واجبان مع جميع الناس بغض النظر عن الدين. حسن الجوار لا يتوقف على المعتقد.',quran:'وَأَحْسِنُوا إِنَّ اللَّهَ يُحِبُّ الْمُحْسِنِينَ',quranRef:'البقرة ٢: ١٩٥',action:'أحسن اليوم إلى جارك مهما كان دينه'},en:{title:'Kindness to Non-Muslims',desc:'Kindness and goodness are obligatory toward all people regardless of religion. Good neighborliness is not contingent on belief.',quran:'And do good — indeed God loves those who do good',quranRef:'Al-Baqarah 2:195',action:'Be kind to your neighbor today regardless of their religion'},fr:{title:'La Bonte Envers les Non-Musulmans',desc:'La bonte et la bienfaisance sont obligatoires envers tous les gens quel que soit leur religion. Le bon voisinage ne depend pas de la croyance.',quran:'Et faites le bien — Dieu aime ceux qui font le bien',quranRef:'Al-Baqarah 2:195',action:'Soyez bon envers votre voisin aujourd\'hui quel que soit sa religion'}},
  {id:12,emoji:'🌙',ar:{title:'مريم في القرآن',desc:'القرآن خصص سورة كاملة باسم مريم عليها السلام وأثنى عليها ثناءً عظيماً. هذا دليل احترام.',quran:'إِنَّ اللَّهَ اصْطَفَاكِ وَطَهَّرَكِ وَاصْطَفَاكِ عَلَىٰ نِسَاءِ الْعَالَمِينَ',quranRef:'آل عمران ٣: ٤٢',action:'اقرأ سورة مريم وتأمل التكريم القرآني لها'},en:{title:'Mary in the Quran',desc:'The Quran dedicated an entire chapter to Mary and praised her greatly. This demonstrates deep respect.',quran:'God has chosen you and purified you and chosen you above the women of all worlds',quranRef:'Aal Imran 3:42',action:'Read Surah Maryam and reflect on the Quranic honoring of her'},fr:{title:'Marie dans le Coran',desc:'Le Coran a consacre un chapitre entier a Marie et l\'a grandement louee. Cela demontre un profond respect.',quran:'Dieu t\'a choisie, purifiee, et choisie au-dessus des femmes de tous les mondes',quranRef:'Aal Imran 3:42',action:'Lisez la sourate Maryam et reflechissez a l\'honneur coranique qui lui est fait'}},
  {id:13,emoji:'🏗️',ar:{title:'تعصب محاكم التفتيش',desc:'محاكم التفتيش في أوروبا أحرقت الآلاف بتهمة الهرطقة. هذا التعصب لم يعرفه التاريخ الإسلامي.',quran:'مَن قَتَلَ نَفْسًا بِغَيْرِ نَفْسٍ فَكَأَنَّمَا قَتَلَ النَّاسَ جَمِيعًا',quranRef:'المائدة ٥: ٣٢',action:'قارن بين تسامح الإسلام وتعصب محاكم التفتيش'},en:{title:'Inquisition Fanaticism',desc:'The Inquisition in Europe burned thousands on charges of heresy. This fanaticism was unknown in Islamic history.',quran:'Whoever kills a soul not in retaliation it is as if they killed all people',quranRef:'Al-Maidah 5:32',action:'Compare Islamic tolerance with the fanaticism of the Inquisition'},fr:{title:'Le Fanatisme de l\'Inquisition',desc:'L\'Inquisition en Europe a brule des milliers de personnes pour heresie. Ce fanatisme etait inconnu dans l\'histoire islamique.',quran:'Quiconque tue une ame sans raison c\'est comme s\'il avait tue l\'humanite entiere',quranRef:'Al-Maidah 5:32',action:'Comparez la tolerance islamique avec le fanatisme de l\'Inquisition'}},
  {id:14,emoji:'🌟',ar:{title:'صلاح الدين والتسامح',desc:'صلاح الدين الأيوبي عندما استعاد القدس لم ينتقم بل عامل المسيحيين بكرم ورحمة.',quran:'وَإِن جَنَحُوا لِلسَّلْمِ فَاجْنَحْ لَهَا',quranRef:'الأنفال ٨: ٦١',action:'اقرأ عن تسامح صلاح الدين عند فتح القدس'},en:{title:'Saladin and Tolerance',desc:'When Saladin recaptured Jerusalem, he did not seek revenge but treated Christians with generosity and mercy.',quran:'And if they incline to peace, then incline to it',quranRef:'Al-Anfal 8:61',action:'Read about Saladin\'s tolerance when he recaptured Jerusalem'},fr:{title:'Saladin et la Tolerance',desc:'Quand Saladin a repris Jerusalem, il n\'a pas cherche la vengeance mais a traite les chretiens avec generosite et misericorde.',quran:'Et s\'ils inclinent vers la paix, incline vers elle aussi',quranRef:'Al-Anfal 8:61',action:'Lisez sur la tolerance de Saladin lors de la reprise de Jerusalem'}},
  {id:15,emoji:'📊',ar:{title:'مقارنة منصفة',desc:'الغزالي يدعو لمقارنة منصفة بين تاريخ المسيحية والإسلام في التعامل مع الآخر.',quran:'يَا أَيُّهَا الَّذِينَ آمَنُوا كُونُوا قَوَّامِينَ بِالْقِسْطِ',quranRef:'النساء ٤: ١٣٥',action:'ابحث بإنصاف عن نماذج التسامح في كلا الدينين'},en:{title:'A Fair Comparison',desc:'Al-Ghazali calls for a fair comparison between the histories of Christianity and Islam in dealing with the other.',quran:'O believers, be persistently standing firm in justice',quranRef:'An-Nisa 4:135',action:'Research fairly models of tolerance in both religions'},fr:{title:'Une Comparaison Equitable',desc:'Al-Ghazali appelle a une comparaison equitable entre les histoires du christianisme et de l\'Islam dans le traitement de l\'autre.',quran:'O croyants, soyez fermement attaches a la justice',quranRef:'An-Nisa 4:135',action:'Recherchez equitablement des modeles de tolerance dans les deux religions'}},
  {id:16,emoji:'🌱',ar:{title:'التسامح ثمرة الإيمان',desc:'التسامح الحقيقي ينبع من الإيمان لا من الضعف. المؤمن القوي يتسامح لأنه واثق بربه.',quran:'وَلَمَن صَبَرَ وَغَفَرَ إِنَّ ذَٰلِكَ لَمِنْ عَزْمِ الْأُمُورِ',quranRef:'الشورى ٤٢: ٤٣',action:'سامح اليوم شخصاً أساء إليك'},en:{title:'Tolerance: Fruit of Faith',desc:'True tolerance springs from faith, not from weakness. The strong believer is tolerant because they trust in God.',quran:'And whoever is patient and forgives, that is truly of the matters requiring resolve',quranRef:'Ash-Shura 42:43',action:'Forgive someone who wronged you today'},fr:{title:'La Tolerance : Fruit de la Foi',desc:'La vraie tolerance nait de la foi, pas de la faiblesse. Le croyant fort est tolerant parce qu\'il a confiance en Dieu.',quran:'Et quiconque est patient et pardonne, c\'est la une marque de caractere',quranRef:'Ash-Shura 42:43',action:'Pardonnez aujourd\'hui a quelqu\'un qui vous a fait du tort'}},
  {id:17,emoji:'🔑',ar:{title:'الحرية الدينية في القرآن',desc:'القرآن يؤكد أن الهداية بيد الله وليست بالإكراه. على الداعية البلاغ فقط.',quran:'لَّسْتَ عَلَيْهِم بِمُصَيْطِرٍ',quranRef:'الغاشية ٨٨: ٢٢',action:'احترم حرية اختيار الآخرين حتى لو اختلفت معهم'},en:{title:'Religious Freedom in the Quran',desc:'The Quran affirms that guidance is in God\'s hands, not through coercion. The caller\'s duty is only to convey.',quran:'You are not a controller over them',quranRef:'Al-Ghashiyah 88:22',action:'Respect others\' freedom of choice even if you disagree'},fr:{title:'La Liberte Religieuse dans le Coran',desc:'Le Coran affirme que la guidance est entre les mains de Dieu, pas par la coercition. Le devoir du predicateur est seulement de transmettre.',quran:'Tu n\'es pas un dominateur sur eux',quranRef:'Al-Ghashiyah 88:22',action:'Respectez la liberte de choix des autres meme si vous n\'etes pas d\'accord'}},
  {id:18,emoji:'📚',ar:{title:'علماء مسلمون ويهود ومسيحيون',desc:'في العصر الذهبي الإسلامي تعاون العلماء من مختلف الأديان في ترجمة العلوم وتطويرها.',quran:'وَجَعَلْنَاكُمْ شُعُوبًا وَقَبَائِلَ لِتَعَارَفُوا',quranRef:'الحجرات ٤٩: ١٣',action:'ابحث عن مثال للتعاون العلمي بين أديان مختلفة'},en:{title:'Muslim, Jewish, and Christian Scholars',desc:'In the Islamic Golden Age, scholars from different religions collaborated in translating and advancing sciences.',quran:'And We made you nations and tribes to know one another',quranRef:'Al-Hujurat 49:13',action:'Research an example of scientific collaboration between different faiths'},fr:{title:'Savants Musulmans, Juifs et Chretiens',desc:'A l\'age d\'or islamique, des savants de differentes religions ont collabore pour traduire et faire avancer les sciences.',quran:'Et Nous avons fait de vous des nations et des tribus pour que vous vous connaissiez',quranRef:'Al-Hujurat 49:13',action:'Recherchez un exemple de collaboration scientifique entre differentes religions'}},
  {id:19,emoji:'🤲',ar:{title:'الدعاء للآخرين',desc:'النبي كان يدعو لهداية غير المسلمين لا لهلاكهم. الداعية يحب الخير لجميع البشر.',quran:'فَقُولَا لَهُ قَوْلًا لَّيِّنًا لَّعَلَّهُ يَتَذَكَّرُ أَوْ يَخْشَىٰ',quranRef:'طه ٢٠: ٤٤',action:'ادعُ اليوم بالخير لشخص من دين مختلف'},en:{title:'Praying for Others',desc:'The Prophet used to pray for the guidance of non-Muslims, not for their destruction. The caller loves good for all humanity.',quran:'Speak to him gently — perhaps he may remember or have fear',quranRef:'Taha 20:44',action:'Pray today for the wellbeing of someone of a different faith'},fr:{title:'Prier pour les Autres',desc:'Le Prophete priait pour la guidance des non-musulmans, pas pour leur destruction. Le predicateur aime le bien pour toute l\'humanite.',quran:'Parlez-lui doucement — peut-etre se souviendra-t-il ou aura-t-il crainte',quranRef:'Taha 20:44',action:'Priez aujourd\'hui pour le bien-etre d\'une personne de foi differente'}},
  {id:20,emoji:'🌈',ar:{title:'التسامح طريق السلام',desc:'التعصب يصنع الحروب والتسامح يصنع السلام. الإسلام يدعو للسلام العالمي المبني على العدل والاحترام.',quran:'يَا أَيُّهَا الَّذِينَ آمَنُوا ادْخُلُوا فِي السِّلْمِ كَافَّةً',quranRef:'البقرة ٢: ٢٠٨',action:'انشر رسالة تسامح وسلام اليوم'},en:{title:'Tolerance: The Path to Peace',desc:'Fanaticism creates wars and tolerance creates peace. Islam calls for global peace built on justice and respect.',quran:'O believers, enter into peace completely',quranRef:'Al-Baqarah 2:208',action:'Spread a message of tolerance and peace today'},fr:{title:'La Tolerance : Le Chemin vers la Paix',desc:'Le fanatisme cree les guerres et la tolerance cree la paix. L\'Islam appelle a la paix mondiale fondee sur la justice et le respect.',quran:'O croyants, entrez dans la paix entierement',quranRef:'Al-Baqarah 2:208',action:'Repandez un message de tolerance et de paix aujourd\'hui'}}
];

const TOLERANCE_DATA = [
  {emoji:'🏰',ar:{title:'القدس تحت الحكم الإسلامي',problem:'الصليبيون عند احتلال القدس ذبحوا سكانها',solution:'عمر بن الخطاب وصلاح الدين حافظا على أرواح السكان وكنائسهم'},en:{title:'Jerusalem Under Islamic Rule',problem:'Crusaders massacred Jerusalem\'s inhabitants upon conquest',solution:'Umar and Saladin preserved the lives of inhabitants and their churches'},fr:{title:'Jerusalem Sous la Gouvernance Islamique',problem:'Les Croises ont massacre les habitants de Jerusalem lors de la conquete',solution:'Omar et Saladin ont preserve les vies des habitants et leurs eglises'}},
  {emoji:'🌍',ar:{title:'الأندلس مقابل أوروبا',problem:'أوروبا في العصور الوسطى اضطهدت المخالفين دينياً',solution:'الأندلس كانت ملاذاً آمناً لليهود والمسيحيين تحت الحكم الإسلامي'},en:{title:'Al-Andalus vs Europe',problem:'Medieval Europe persecuted religious dissenters',solution:'Al-Andalus was a safe haven for Jews and Christians under Islamic rule'},fr:{title:'Al-Andalus vs Europe',problem:'L\'Europe medievale persecutait les dissidents religieux',solution:'Al-Andalus etait un havre de paix pour les juifs et chretiens sous la gouvernance islamique'}},
  {emoji:'⚖️',ar:{title:'محاكم التفتيش مقابل القضاء الإسلامي',problem:'محاكم التفتيش أحرقت الآلاف بتهمة الكفر',solution:'القضاء الإسلامي كفل حقوق المتهم ومنع التعذيب'},en:{title:'Inquisition vs Islamic Judiciary',problem:'The Inquisition burned thousands for alleged heresy',solution:'Islamic judiciary guaranteed defendants\' rights and prohibited torture'},fr:{title:'L\'Inquisition vs La Justice Islamique',problem:'L\'Inquisition a brule des milliers pour pretendue heresie',solution:'La justice islamique a garanti les droits des accuses et interdit la torture'}},
  {emoji:'📖',ar:{title:'حرية الكتب مقابل حرقها',problem:'أوروبا أحرقت كتباً كثيرة بما فيها ترجمات القرآن',solution:'المسلمون ترجموا علوم الإغريق وحفظوها من الضياع'},en:{title:'Book Freedom vs Book Burning',problem:'Europe burned many books including Quran translations',solution:'Muslims translated Greek sciences and preserved them from extinction'},fr:{title:'Liberte des Livres vs Autodafe',problem:'L\'Europe a brule de nombreux livres y compris des traductions du Coran',solution:'Les musulmans ont traduit les sciences grecques et les ont preservees de l\'extinction'}},
  {emoji:'🤝',ar:{title:'معاملة الأسرى',problem:'في الحروب الصليبية عوملَ الأسرى المسلمون بقسوة',solution:'الإسلام أمر بإحسان معاملة الأسرى وإطعامهم'},en:{title:'Treatment of Prisoners',problem:'Muslim prisoners were treated harshly during the Crusades',solution:'Islam commanded kindness toward prisoners and feeding them'},fr:{title:'Traitement des Prisonniers',problem:'Les prisonniers musulmans etaient traites durement pendant les Croisades',solution:'L\'Islam a ordonne la bonte envers les prisonniers et de les nourrir'}},
  {emoji:'👩',ar:{title:'حقوق المرأة المقارنة',problem:'أوروبا حتى القرن ١٩ لم تعترف بحق المرأة في الملكية',solution:'الإسلام كفل حق المرأة في الملكية والإرث منذ ١٤ قرناً'},en:{title:'Women\'s Rights Compared',problem:'Europe until the 19th century did not recognize women\'s property rights',solution:'Islam guaranteed women\'s property and inheritance rights 14 centuries ago'},fr:{title:'Droits des Femmes Compares',problem:'L\'Europe jusqu\'au 19e siecle ne reconnaissait pas le droit de propriete des femmes',solution:'L\'Islam a garanti les droits de propriete et d\'heritage des femmes depuis 14 siecles'}},
  {emoji:'🌱',ar:{title:'التعايش في مصر',problem:'البعض يزعم أن الأقباط مضطهدون تاريخياً',solution:'الأقباط عاشوا في مصر الإسلامية محتفظين بكنائسهم وحقوقهم لقرون'},en:{title:'Coexistence in Egypt',problem:'Some claim Copts have been historically persecuted',solution:'Copts lived in Islamic Egypt retaining their churches and rights for centuries'},fr:{title:'La Coexistence en Egypte',problem:'Certains pretendent que les Coptes ont ete historiquement persecutes',solution:'Les Coptes ont vecu en Egypte islamique en conservant leurs eglises et droits pendant des siecles'}},
  {emoji:'🔑',ar:{title:'مفاتيح كنيسة القيامة',problem:'من يحرس أقدس كنيسة مسيحية في القدس؟',solution:'عائلة مسلمة تحمل مفاتيح كنيسة القيامة في القدس منذ قرون — رمز التسامح'},en:{title:'Keys to the Holy Sepulchre',problem:'Who guards the holiest Christian church in Jerusalem?',solution:'A Muslim family has held the keys to the Church of the Holy Sepulchre for centuries — a symbol of tolerance'},fr:{title:'Les Cles du Saint-Sepulcre',problem:'Qui garde la plus sainte eglise chretienne a Jerusalem ?',solution:'Une famille musulmane detient les cles de l\'Eglise du Saint-Sepulcre depuis des siecles — un symbole de tolerance'}}
];

const HABITS = [
  {emoji:'🕊️',ar:{label:'عامل الجميع باحترام اليوم',source:'من الكتاب: لا إكراه في الدين'},en:{label:'Treat everyone with respect today',source:'From the book: No compulsion in religion'},fr:{label:'Traitez tout le monde avec respect',source:'Du livre : Pas de contrainte en religion'}},
  {emoji:'🤝',ar:{label:'تعرف على ثقافة مختلفة',source:'من الكتاب: التعارف لا التصادم'},en:{label:'Learn about a different culture',source:'From the book: Knowing, not clashing'},fr:{label:'Decouvrez une culture differente',source:'Du livre : Se connaitre, pas se heurter'}},
  {emoji:'💬',ar:{label:'ابحث عن قاسم مشترك مع مختلف',source:'من الكتاب: الحوار بين الأديان'},en:{label:'Find common ground with someone different',source:'From the book: Interfaith dialogue'},fr:{label:'Trouvez un terrain commun avec quelqu\'un de different',source:'Du livre : Le dialogue interreligieux'}},
  {emoji:'❤️',ar:{label:'أحسن إلى جارك مهما كان دينه',source:'من الكتاب: البر والإحسان'},en:{label:'Be kind to your neighbor regardless of faith',source:'From the book: Kindness to all'},fr:{label:'Soyez bon envers votre voisin quelle que soit sa foi',source:'Du livre : La bonte envers tous'}},
  {emoji:'📖',ar:{label:'اقرأ صفحة عن التسامح في الإسلام',source:'من الكتاب: التسامح ثمرة الإيمان'},en:{label:'Read a page about tolerance in Islam',source:'From the book: Tolerance is fruit of faith'},fr:{label:'Lisez une page sur la tolerance en Islam',source:'Du livre : La tolerance fruit de la foi'}},
  {emoji:'🤲',ar:{label:'ادعُ بالخير لشخص من دين مختلف',source:'من الكتاب: الدعاء للآخرين'},en:{label:'Pray for someone of a different faith',source:'From the book: Praying for others'},fr:{label:'Priez pour quelqu\'un de foi differente',source:'Du livre : Prier pour les autres'}},
  {emoji:'⚖️',ar:{label:'كن عادلاً في حكمك على الآخرين',source:'من الكتاب: العدل مع المخالف'},en:{label:'Be fair in judging others',source:'From the book: Justice with opponents'},fr:{label:'Soyez equitable en jugeant les autres',source:'Du livre : La justice envers les opposants'}},
  {emoji:'🌈',ar:{label:'انشر رسالة سلام وتسامح',source:'من الكتاب: التسامح طريق السلام'},en:{label:'Spread a message of peace and tolerance',source:'From the book: Tolerance is the path to peace'},fr:{label:'Repandez un message de paix et tolerance',source:'Du livre : La tolerance chemin vers la paix'}}
];

const QUIZ = [
  {ar:'هل تحترم حرية المعتقد عند الآخرين؟',en:'Do you respect others\' freedom of belief?',fr:'Respectez-vous la liberte de croyance des autres ?'},
  {ar:'هل تشعر بالتفوق على أصحاب الديانات الأخرى؟',en:'Do you feel superior to people of other faiths?',fr:'Vous sentez-vous superieur aux personnes d\'autres religions ?'},
  {ar:'هل تعامل جيرانك من غير المسلمين بإحسان؟',en:'Do you treat your non-Muslim neighbors with kindness?',fr:'Traitez-vous vos voisins non-musulmans avec bonte ?'},
  {ar:'هل تتعصب لرأيك ولا تقبل الحوار؟',en:'Are you dogmatic and refuse dialogue?',fr:'Etes-vous dogmatique et refusez-vous le dialogue ?'},
  {ar:'هل تعرف حقوق غير المسلمين في الإسلام؟',en:'Do you know the rights of non-Muslims in Islam?',fr:'Connaissez-vous les droits des non-musulmans en Islam ?'},
  {ar:'هل تدعو بالخير لجميع الناس؟',en:'Do you pray for the good of all people?',fr:'Priez-vous pour le bien de tous les gens ?'},
  {ar:'هل تبحث عن القواسم المشتركة مع المختلفين؟',en:'Do you seek common ground with those who differ?',fr:'Cherchez-vous un terrain commun avec ceux qui different ?'},
  {ar:'هل تؤمن بالعدل حتى مع من يخالفك؟',en:'Do you believe in justice even with those who oppose you?',fr:'Croyez-vous en la justice meme envers ceux qui vous opposent ?'},
  {ar:'هل تسامح من أساء إليك؟',en:'Do you forgive those who wrong you?',fr:'Pardonnez-vous a ceux qui vous font du tort ?'},
  {ar:'هل تنشر رسالة السلام والتسامح في محيطك؟',en:'Do you spread the message of peace and tolerance around you?',fr:'Repandez-vous le message de paix et tolerance autour de vous ?'}
];

const DUAS = [
  {ar:{label:'دعاء السلام',text:'اللَّهُمَّ أَنتَ السَّلَامُ وَمِنكَ السَّلَامُ',tr:'اللهم انشر السلام بين الناس جميعاً'},en:{label:'Dua for Peace',text:'اللَّهُمَّ أَنتَ السَّلَامُ وَمِنكَ السَّلَامُ',tr:'O God, You are Peace and from You comes peace'},fr:{label:'Dua pour la Paix',text:'اللَّهُمَّ أَنتَ السَّلَامُ وَمِنكَ السَّلَامُ',tr:'O Dieu, Tu es la Paix et de Toi vient la paix'}},
  {ar:{label:'دعاء الهداية',text:'اللَّهُمَّ اهْدِنِي وَاهْدِ بِي',tr:'اللهم اهدني واجعلني سبباً لهداية الآخرين'},en:{label:'Dua for Guidance',text:'اللَّهُمَّ اهْدِنِي وَاهْدِ بِي',tr:'O God, guide me and make me a means of guiding others'},fr:{label:'Dua pour la Guidance',text:'اللَّهُمَّ اهْدِنِي وَاهْدِ بِي',tr:'O Dieu, guide-moi et fais de moi un moyen de guider les autres'}},
  {ar:{label:'دعاء الرحمة',text:'رَبَّنَا وَسِعْتَ كُلَّ شَيْءٍ رَّحْمَةً وَعِلْمًا',tr:'ربنا رحمتك وسعت كل شيء'},en:{label:'Dua for Mercy',text:'رَبَّنَا وَسِعْتَ كُلَّ شَيْءٍ رَّحْمَةً وَعِلْمًا',tr:'Our Lord, Your mercy and knowledge encompass all things'},fr:{label:'Dua pour la Misericorde',text:'رَبَّنَا وَسِعْتَ كُلَّ شَيْءٍ رَّحْمَةً وَعِلْمًا',tr:'Notre Seigneur, Ta misericorde et Ton savoir englobent toute chose'}},
  {ar:{label:'دعاء الصبر',text:'رَبَّنَا أَفْرِغْ عَلَيْنَا صَبْرًا',tr:'اللهم ارزقنا الصبر والتسامح'},en:{label:'Dua for Patience',text:'رَبَّنَا أَفْرِغْ عَلَيْنَا صَبْرًا',tr:'Our Lord, pour patience upon us'},fr:{label:'Dua pour la Patience',text:'رَبَّنَا أَفْرِغْ عَلَيْنَا صَبْرًا',tr:'Notre Seigneur, deverse sur nous la patience'}},
  {ar:{label:'دعاء العفو',text:'اللَّهُمَّ إِنَّكَ عَفُوٌّ تُحِبُّ الْعَفْوَ فَاعْفُ عَنِّي',tr:'اللهم اغفر لي وعلمني العفو'},en:{label:'Dua for Pardon',text:'اللَّهُمَّ إِنَّكَ عَفُوٌّ تُحِبُّ الْعَفْوَ فَاعْفُ عَنِّي',tr:'O God, You are the Pardoner who loves pardon, so pardon me'},fr:{label:'Dua pour le Pardon',text:'اللَّهُمَّ إِنَّكَ عَفُوٌّ تُحِبُّ الْعَفْوَ فَاعْفُ عَنِّي',tr:'O Dieu, Tu es le Pardonneur qui aime le pardon, alors pardonne-moi'}},
  {ar:{label:'دعاء الألفة',text:'اللَّهُمَّ أَلِّفْ بَيْنَ قُلُوبِنَا',tr:'اللهم اجمع قلوب الناس على الخير'},en:{label:'Dua for Unity',text:'اللَّهُمَّ أَلِّفْ بَيْنَ قُلُوبِنَا',tr:'O God, unite our hearts'},fr:{label:'Dua pour l\'Unite',text:'اللَّهُمَّ أَلِّفْ بَيْنَ قُلُوبِنَا',tr:'O Dieu, unis nos coeurs'}},
  {ar:{label:'دعاء الحكمة',text:'رَبِّ هَبْ لِي حُكْمًا وَأَلْحِقْنِي بِالصَّالِحِينَ',tr:'رب ارزقني الحكمة في التعامل'},en:{label:'Dua for Wisdom',text:'رَبِّ هَبْ لِي حُكْمًا وَأَلْحِقْنِي بِالصَّالِحِينَ',tr:'My Lord, grant me wisdom and join me with the righteous'},fr:{label:'Dua pour la Sagesse',text:'رَبِّ هَبْ لِي حُكْمًا وَأَلْحِقْنِي بِالصَّالِحِينَ',tr:'Mon Seigneur, accorde-moi la sagesse et joins-moi aux vertueux'}},
  {ar:{label:'دعاء التوفيق',text:'رَبِّ اشْرَحْ لِي صَدْرِي وَيَسِّرْ لِي أَمْرِي',tr:'رب يسر لي أمر التسامح والبناء'},en:{label:'Dua for Facilitation',text:'رَبِّ اشْرَحْ لِي صَدْرِي وَيَسِّرْ لِي أَمْرِي',tr:'My Lord, expand my chest and ease my affairs'},fr:{label:'Dua pour la Facilitation',text:'رَبِّ اشْرَحْ لِي صَدْرِي وَيَسِّرْ لِي أَمْرِي',tr:'Mon Seigneur, ouvre-moi ma poitrine et facilite mes affaires'}}
];

let lang = localStorage.getItem('tt-lang') || 'ar';
let theme = localStorage.getItem('tt-theme') || 'amethyst';
const themes = ['amethyst','night','lavender'];
const themeIcons = ['💜','🌙','🌸'];
const themeNames = {amethyst:'💜 Amethyst',night:'🌙 Night',lavender:'🌸 Lavender'};
let currentCardIdx = 0;

document.addEventListener('DOMContentLoaded', () => {
  setTheme(theme); setLang(lang); initSplash(); initTabs(); initScrollTop();
  renderHome(); renderCards(); renderTolerance(); renderHabits(); renderQuiz(); renderAbout(); renderHelp(); renderDuas(); initScrollReveal(); initKeyboardNav();
});

function initSplash() { let count = 5; const el = document.getElementById('splashCount'); const featuresEl = document.getElementById('splashFeatures'); if (featuresEl) { featuresEl.innerHTML = T[lang].splashFeatures.map((f, i) => `<div class="splash-feature" style="animation-delay:${0.3 + i * 0.3}s">${f}</div>`).join(''); } const interval = setInterval(() => { count--; if (el) el.textContent = count; if (count <= 0) { dismissSplash(); clearInterval(interval); } }, 1000); }
function dismissSplash() { const s = document.getElementById('splash'); if (s) { s.classList.add('hidden'); setTimeout(() => s.style.display = 'none', 500); } playSound('click'); }

function setLang(l) {
  lang = l; localStorage.setItem('tt-lang', l); const isRTL = l === 'ar'; document.documentElement.lang = l; document.documentElement.dir = isRTL ? 'rtl' : 'ltr'; document.body.dir = isRTL ? 'rtl' : 'ltr';
  document.querySelectorAll('.lang-opt').forEach(b => b.classList.toggle('active', b.dataset.lang === l));
  const t = T[l]; const set = (id, val) => { const el = document.getElementById(id); if (el) el.textContent = val; };
  set('appTitle', t.appTitle); set('splashSub', t.splashSub); set('splashHint', t.splashHint);
  set('tabHome', t.tabHome); set('tabCards', t.tabCards); set('tabTolerance', t.tabTolerance);
  set('tabHabits', t.tabHabits); set('tabQuiz', t.tabQuiz); set('tabAbout', t.tabAbout);
  set('cardsTitle', t.cardsTitle); set('cardsDesc', t.cardsDesc); set('toleranceTitle', t.toleranceTitle); set('toleranceDesc', t.toleranceDesc);
  set('habitsTitle', t.habitsTitle); set('habitsDesc', t.habitsDesc); set('quizTitle', t.quizTitle); set('quizDesc', t.quizDesc);
  set('helpTitle', t.helpTitle); set('duaPanelTitle', t.duaPanelTitle); set('habitsReset', t.resetBtn);
  renderHome(); renderCards(); renderTolerance(); renderHabits(); renderQuiz(); renderAbout(); renderHelp(); renderDuas();
  const featuresEl = document.getElementById('splashFeatures'); if (featuresEl) { featuresEl.innerHTML = T[l].splashFeatures.map((f, i) => `<div class="splash-feature" style="animation-delay:${0.3 + i * 0.3}s">${f}</div>`).join(''); }
}

function setTheme(t) { theme = t; document.documentElement.dataset.theme = t; localStorage.setItem('tt-theme', t); const idx = themes.indexOf(t); const el = document.getElementById('themeIcon'); if (el) el.textContent = themeIcons[idx]; }
function cycleTheme() { const idx = (themes.indexOf(theme) + 1) % themes.length; setTheme(themes[idx]); showToast(themeNames[themes[idx]]); playSound('theme'); }
function initTabs() { document.querySelectorAll('.tab').forEach(tab => { tab.addEventListener('click', () => { document.querySelectorAll('.tab').forEach(t => t.classList.remove('active')); document.querySelectorAll('.panel').forEach(p => p.classList.remove('active')); tab.classList.add('active'); const panel = document.getElementById('panel-' + tab.dataset.tab); if (panel) panel.classList.add('active'); window.scrollTo({top: 0, behavior: 'smooth'}); playSound('click'); }); }); }

function renderHome() { const t = T[lang]; const dayIdx = new Date().getDate() % CARDS.length; const c = CARDS[dayIdx]; const cd = c[lang]; document.getElementById('dailyCard').innerHTML = `<div class="daily-label">${t.dailyLabel}</div><div class="daily-title">${cd.title}</div><div class="daily-body">${cd.desc}</div><div class="daily-action" onclick="document.querySelector('[data-tab=cards]').click()">${t.tabCards} &#8594;</div>`; const sections = [{icon:'🕊️',tab:'cards',title:t.tabCards,desc:lang==='ar'?'٢٠ بطاقة تسامح':lang==='fr'?'20 cartes':'20 cards'},{icon:'⚖️',tab:'tolerance',title:t.tabTolerance,desc:lang==='ar'?'نماذج تاريخية':lang==='fr'?'Modeles historiques':'Historical models'},{icon:'📋',tab:'habits',title:t.tabHabits,desc:lang==='ar'?'تتبع يومي':lang==='fr'?'Suivi quotidien':'Daily tracking'},{icon:'🤔',tab:'quiz',title:t.tabQuiz,desc:lang==='ar'?'اختبر نفسك':lang==='fr'?'Testez-vous':'Test yourself'},{icon:'📖',tab:'about',title:t.tabAbout,desc:lang==='ar'?'عن الكتاب':lang==='fr'?'Le livre':'About the book'}]; document.getElementById('homeGrid').innerHTML = sections.map(s => `<div class="home-card" onclick="document.querySelector('[data-tab=${s.tab}]').click()"><span class="hc-icon">${s.icon}</span><div class="hc-title">${s.title}</div><div class="hc-desc">${s.desc}</div></div>`).join(''); }

function renderCards() { const t = T[lang]; const searchBar = `<div class="search-bar"><input type="text" id="cardsSearch" class="search-input" placeholder="${t.searchPlaceholder}" oninput="filterCards(this.value)"><span class="search-icon">🔍</span></div>`; const cards = CARDS.map((c, i) => { const d = c[lang]; return `<div class="principle-card scroll-reveal" id="card-${c.id}" data-search="${d.title.toLowerCase()}"><div class="principle-head" onclick="toggleCard('card-${c.id}')"><span class="principle-num">${c.id}</span><span class="principle-emoji">${c.emoji}</span><span class="principle-title">${d.title}</span><span class="principle-chev">&#9660;</span></div><div class="principle-body"><div class="principle-inner"><p class="principle-desc">${d.desc}</p><div class="verse-box"><div class="verse-arabic">${d.quran}</div><div class="verse-ref">${d.quranRef}</div></div><div class="action-box"><span class="action-icon">💡</span><span>${d.action}</span></div><button class="share-btn" onclick="event.stopPropagation();shareCard(${i})"><span class="share-icon">&#128279;</span> ${t.share}</button></div></div></div>`; }).join(''); document.getElementById('cardsContainer').innerHTML = searchBar + cards; }
function filterCards(query) { const q = query.toLowerCase().trim(); document.querySelectorAll('.principle-card').forEach(card => { const s = card.dataset.search || ''; const t = card.querySelector('.principle-title'); card.style.display = (!q || s.includes(q) || (t && t.textContent.toLowerCase().includes(q))) ? '' : 'none'; }); }
async function shareCard(idx) { const c = CARDS[idx]; const d = c[lang]; const text = `${c.emoji} ${d.title}\n\n${d.desc}\n\n📖 ${d.quran}\n\n💡 ${d.action}\n\n— التعصب والتسامح | Fanaticism & Tolerance`; if (navigator.share) { try { await navigator.share({ title: d.title, text }); } catch(e) {} } else { try { await navigator.clipboard.writeText(text); showToast(lang === 'ar' ? 'تم النسخ!' : lang === 'fr' ? 'Copie !' : 'Copied!'); } catch(e) { showToast('Could not copy'); } } }

function renderTolerance() { document.getElementById('toleranceContainer').innerHTML = TOLERANCE_DATA.map(r => { const d = r[lang]; return `<div class="anxiety-card scroll-reveal"><div class="anxiety-header"><span class="anxiety-emoji">${r.emoji}</span><span class="anxiety-title">${d.title}</span></div><div class="anxiety-problem"><span class="anxiety-label">${lang==='ar'?'❌ التعصب':lang==='fr'?'❌ Le Fanatisme':'❌ Fanaticism'}</span>${d.problem}</div><div class="anxiety-solution"><span class="anxiety-label">${lang==='ar'?'✅ التسامح':lang==='fr'?'✅ La Tolerance':'✅ Tolerance'}</span>${d.solution}</div></div>`; }).join(''); }

function renderHabits() { const today = new Date().toDateString(); let hs = JSON.parse(localStorage.getItem('tt-habits') || '{}'); if (hs.date !== today) { updateStreak(hs); hs = { date: today, done: [] }; localStorage.setItem('tt-habits', JSON.stringify(hs)); } const streak = getStreak(); const streakHTML = streak > 0 ? `<div class="streak-badge">🔥 ${streak} ${T[lang].streakMsg}</div>` : ''; document.getElementById('habitsContainer').innerHTML = HABITS.map((h, i) => { const d = h[lang]; const isDone = hs.done.includes(i); return `<div class="habit-item ${isDone ? 'done' : ''}" onclick="toggleHabit(${i})"><span class="habit-check">${isDone ? '&#10003;' : ''}</span><span class="habit-emoji">${h.emoji}</span><div><div class="habit-label">${d.label}</div><div class="habit-source">${d.source}</div></div></div>`; }).join(''); const streakEl = document.getElementById('streakBadge'); if (streakEl) streakEl.innerHTML = streakHTML; updateHabitsProgress(hs); }
function toggleHabit(i) { const today = new Date().toDateString(); let hs = JSON.parse(localStorage.getItem('tt-habits') || '{}'); if (hs.date !== today) hs = { date: today, done: [] }; const idx = hs.done.indexOf(i); if (idx > -1) hs.done.splice(idx, 1); else hs.done.push(i); localStorage.setItem('tt-habits', JSON.stringify(hs)); renderHabits(); playSound(idx > -1 ? 'click' : 'success'); if (hs.done.length === HABITS.length) { launchConfetti(); showToast(T[lang].allDone); } }
function resetHabits() { localStorage.setItem('tt-habits', JSON.stringify({ date: new Date().toDateString(), done: [] })); renderHabits(); showToast(lang === 'ar' ? 'تم إعادة التعيين' : lang === 'fr' ? 'Reinitialise' : 'Reset'); }
function updateHabitsProgress(hs) { const done = hs.done.length; const total = HABITS.length; const pct = total > 0 ? (done / total * 100) : 0; const fill = document.getElementById('habitsFill'); const txt = document.getElementById('habitsText'); if (fill) fill.style.width = pct + '%'; if (txt) txt.textContent = `${done}/${total}`; }
function updateStreak(prev) { let sd = JSON.parse(localStorage.getItem('tt-streak') || '{"count":0,"lastDate":""}'); if (prev && prev.done && prev.done.length === HABITS.length && prev.date) { const y = new Date(); y.setDate(y.getDate() - 1); if (prev.date === y.toDateString()) sd.count++; else if (prev.date !== new Date().toDateString()) sd.count = prev.done.length === HABITS.length ? 1 : 0; sd.lastDate = prev.date; } else if (prev && prev.date) { sd.count = 0; sd.lastDate = prev.date; } localStorage.setItem('tt-streak', JSON.stringify(sd)); }
function getStreak() { return JSON.parse(localStorage.getItem('tt-streak') || '{"count":0}').count; }
function launchConfetti() { const canvas = document.getElementById('confettiCanvas'); if (!canvas) return; canvas.style.display = 'block'; const ctx = canvas.getContext('2d'); canvas.width = window.innerWidth; canvas.height = window.innerHeight; const particles = []; const colors = ['#6A1B9A','#AB47BC','#CE93D8','#E1BEE7','#66BB6A','#FFA726','#FFD54F']; for (let i = 0; i < 120; i++) particles.push({x:Math.random()*canvas.width,y:Math.random()*canvas.height-canvas.height,w:Math.random()*10+5,h:Math.random()*6+3,color:colors[Math.floor(Math.random()*colors.length)],vx:(Math.random()-.5)*4,vy:Math.random()*3+2,rot:Math.random()*360,rotSpeed:(Math.random()-.5)*10}); let frame = 0; function draw() { ctx.clearRect(0,0,canvas.width,canvas.height); particles.forEach(p => { p.x+=p.vx; p.y+=p.vy; p.rot+=p.rotSpeed; ctx.save(); ctx.translate(p.x,p.y); ctx.rotate(p.rot*Math.PI/180); ctx.fillStyle=p.color; ctx.fillRect(-p.w/2,-p.h/2,p.w,p.h); ctx.restore(); }); frame++; if (frame < 120) requestAnimationFrame(draw); else { ctx.clearRect(0,0,canvas.width,canvas.height); canvas.style.display='none'; } } draw(); }

function renderQuiz() { const t = T[lang]; document.getElementById('quizContainer').innerHTML = QUIZ.map((q, i) => `<div class="quiz-question scroll-reveal" id="quiz-q-${i}"><div class="quiz-q-text">${i+1}. ${q[lang]}</div><div class="quiz-options"><button class="quiz-opt" onclick="selectQuizOpt(${i},2)">${t.yes}</button><button class="quiz-opt" onclick="selectQuizOpt(${i},1)">${t.sometimes}</button><button class="quiz-opt" onclick="selectQuizOpt(${i},0)">${t.no}</button></div></div>`).join('') + `<button class="quiz-submit" onclick="submitQuiz()">${t.submitQuiz}</button>`; document.getElementById('quizResult').classList.add('hidden'); window._quizAnswers = {}; }
function selectQuizOpt(qi, val) { window._quizAnswers[qi] = val; document.querySelectorAll(`#quiz-q-${qi} .quiz-opt`).forEach((o, oi) => { o.classList.toggle('selected', [2,1,0][oi] === val); }); playSound('click'); }
function submitQuiz() { const answers = window._quizAnswers || {}; if (Object.keys(answers).length < QUIZ.length) { showToast(lang === 'ar' ? 'أجب على جميع الأسئلة' : lang === 'fr' ? 'Repondez a toutes les questions' : 'Answer all questions'); return; } const invertedQs = [1, 3]; let score = 0; Object.entries(answers).forEach(([qi, v]) => { score += invertedQs.includes(parseInt(qi)) ? (2 - v) : v; }); const max = QUIZ.length * 2; const pct = Math.round(score / max * 100); let emoji, title, desc; if (pct >= 75) { emoji = '🕊️'; title = lang==='ar'?'متسامح حقيقي!':lang==='fr'?'Vraiment tolerant !':'Truly Tolerant!'; desc = lang==='ar'?'أنت نموذج في التسامح. استمر في نشر السلام!':lang==='fr'?'Vous etes un modele de tolerance. Continuez !':'You are a model of tolerance. Keep spreading peace!'; } else if (pct >= 50) { emoji = '🌱'; title = lang==='ar'?'على الطريق':lang==='fr'?'Sur la bonne voie':'On the Path'; desc = lang==='ar'?'أنت تسير نحو التسامح. واصل القراءة والتطبيق.':lang==='fr'?'Vous allez vers la tolerance. Continuez a lire et pratiquer.':'You\'re moving toward tolerance. Keep reading and practicing.'; } else { emoji = '📚'; title = lang==='ar'?'ابدأ رحلة التسامح':lang==='fr'?'Commencez le voyage':'Start the Journey'; desc = lang==='ar'?'التسامح يحتاج تعلماً وممارسة. ابدأ ببطاقات التسامح.':lang==='fr'?'La tolerance necessite apprentissage et pratique. Commencez par les cartes.':'Tolerance needs learning and practice. Start with the tolerance cards.'; } const result = document.getElementById('quizResult'); result.classList.remove('hidden'); result.innerHTML = `<div class="qr-emoji">${emoji}</div><div class="qr-score">${pct}%</div><div class="qr-title">${title}</div><div class="qr-desc">${desc}</div><button class="quiz-submit" onclick="renderQuiz()" style="margin-top:16px">${T[lang].quizAgain}</button>`; result.scrollIntoView({ behavior: 'smooth' }); playSound('success'); }

function renderAbout() { const about = { ar: { disclaimerTitle:'⚠️ تنبيه مهم',disclaimer:'لست عالماً ولا مفتياً. هذا جهد متواضع من مسلم يحب كتب الشيخ الغزالي. ليست فتوى.',authorName:'الشيخ محمد الغزالي',authorDates:'١٩١٧ — ١٩٩٦',authorBio:'عالم ومفكر إسلامي مصري. ألّف أكثر من ٩٤ كتاباً. عُرف بالتجديد والاعتدال والدفاع عن الإسلام.',bookTitle:'عن الكتاب',bookDesc:'"التعصب والتسامح بين المسيحية والإسلام" كتاب يقارن فيه الشيخ الغزالي بين تعامل المسيحية والإسلام مع الآخر عبر التاريخ، مستشهداً بنماذج تاريخية موثقة في التسامح والتعصب.',sourcesTitle:'المصادر',sources:['كتاب "التعصب والتسامح" — الشيخ محمد الغزالي','القرآن الكريم','صحيح البخاري ومسلم'],contact:'تواصل: abdelhak.bourdim@gmail.com'}, en: { disclaimerTitle:'⚠️ Important Notice',disclaimer:'I am not a scholar or mufti. This is a humble effort. Not a fatwa.',authorName:'Sheikh Mohammed al-Ghazali',authorDates:'1917 — 1996',authorBio:'Egyptian Islamic scholar and thinker. Author of 94+ books. Known for renewal, moderation, and defending Islam.',bookTitle:'About the Book',bookDesc:'"Fanaticism and Tolerance Between Christianity and Islam" compares how Christianity and Islam have dealt with the other throughout history, citing documented historical examples of tolerance and fanaticism.',sourcesTitle:'Sources',sources:['"Fanaticism and Tolerance" — Sheikh Mohammed al-Ghazali','The Holy Quran','Sahih al-Bukhari and Muslim'],contact:'Contact: abdelhak.bourdim@gmail.com'}, fr: { disclaimerTitle:'⚠️ Avis Important',disclaimer:'Je ne suis ni savant ni mufti. C\'est un effort humble. Pas une fatwa.',authorName:'Sheikh Mohammed al-Ghazali',authorDates:'1917 — 1996',authorBio:'Savant et penseur islamique egyptien. Auteur de plus de 94 livres. Connu pour le renouveau et la moderation.',bookTitle:'A Propos du Livre',bookDesc:'« Fanatisme et Tolerance entre Christianisme et Islam » compare comment le christianisme et l\'Islam ont traite l\'autre a travers l\'histoire, citant des exemples historiques documentes.',sourcesTitle:'Sources',sources:['« Fanatisme et Tolerance » — Sheikh Mohammed al-Ghazali','Le Saint Coran','Sahih al-Bukhari et Muslim'],contact:'Contact : abdelhak.bourdim@gmail.com'} }; const a = about[lang]; document.getElementById('aboutContainer').innerHTML = `<div class="about-disclaimer"><div class="about-disclaimer-title">${a.disclaimerTitle}</div><p>${a.disclaimer}</p></div><div class="about-author"><span class="about-author-icon">📚</span><div class="about-author-info"><div class="about-author-name">${a.authorName}</div><div class="about-author-dates">${a.authorDates}</div><div class="about-author-bio">${a.authorBio}</div></div></div><div class="about-section"><div class="about-section-title">${a.bookTitle}</div><p class="about-text">${a.bookDesc}</p></div><div class="about-section"><div class="about-section-title">${a.sourcesTitle}</div>${a.sources.map(s => `<p class="about-text">&#8226; ${s}</p>`).join('')}</div><div class="about-section"><p class="about-text">${a.contact}</p></div>`; }

function renderHelp() { const help = { ar: [{title:'⚠️ تنبيه',body:'لست عالماً. هذا جهد متواضع لنشر حكمة الشيخ الغزالي.'},{title:'📚 المصادر',body:'كتاب "التعصب والتسامح"، القرآن الكريم، السنة.'},{title:'✨ المميزات',body:'ثلاث لغات، ٣ أنماط، ٢٠ بطاقة، ٨ نماذج تاريخية، تتبع العادات، اختبار، ٨ أدعية.'}], en: [{title:'⚠️ Disclaimer',body:'I am not a scholar. This is a humble effort.'},{title:'📚 Sources',body:'"Fanaticism and Tolerance" by Sheikh al-Ghazali, Quran, Sunnah.'},{title:'✨ Features',body:'Three languages, 3 themes, 20 cards, 8 historical models, habit tracker, quiz, 8 duas.'}], fr: [{title:'⚠️ Avertissement',body:'Je ne suis pas un savant. C\'est un effort humble.'},{title:'📚 Sources',body:'« Fanatisme et Tolerance » par Sheikh al-Ghazali, Coran, Sunnah.'},{title:'✨ Fonctionnalites',body:'Trois langues, 3 themes, 20 cartes, 8 modeles, suivi habitudes, quiz, 8 duas.'}] }; document.getElementById('helpBody').innerHTML = help[lang].map(h => `<div class="help-item"><div class="help-item-title">${h.title}</div><div>${h.body}</div></div>`).join(''); }
function renderDuas() { document.getElementById('duaPanelContent').innerHTML = DUAS.map(d => { const dd = d[lang]; return `<div class="dua-item"><div class="dua-item-label">${dd.label}</div><div class="dua-item-ar">${dd.text}</div><div class="dua-item-tr">${dd.tr}</div></div>`; }).join(''); }
function initScrollReveal() { if (!('IntersectionObserver' in window)) return; const observer = new IntersectionObserver((entries) => { entries.forEach(entry => { if (entry.isIntersecting) { entry.target.classList.add('revealed'); observer.unobserve(entry.target); } }); }, { threshold: 0.08, rootMargin: '0px 0px -40px 0px' }); function observeAll() { document.querySelectorAll('.scroll-reveal:not(.revealed)').forEach(el => observer.observe(el)); } observeAll(); document.querySelectorAll('.tab').forEach(tab => { tab.addEventListener('click', () => setTimeout(observeAll, 100)); }); }
function initKeyboardNav() { document.addEventListener('keydown', (e) => { if (e.key === 'Escape') { const hp = document.getElementById('helpPanel'); if (!hp.classList.contains('hidden')) { toggleHelp(); return; } const dp = document.getElementById('duaPanel'); if (!dp.classList.contains('hidden')) { toggleDuaPanel(); return; } document.querySelectorAll('.principle-card.open').forEach(c => c.classList.remove('open')); } if (e.key === 'ArrowRight' || e.key === 'ArrowLeft') { const panel = document.getElementById('panel-cards'); if (!panel || !panel.classList.contains('active')) return; if (document.activeElement && document.activeElement.id === 'cardsSearch') return; e.preventDefault(); const cards = Array.from(document.querySelectorAll('.principle-card')).filter(c => c.style.display !== 'none'); if (!cards.length) return; if (currentCardIdx >= 0 && currentCardIdx < cards.length) cards[currentCardIdx].classList.remove('open'); const dir = (document.documentElement.dir === 'rtl') ? (e.key === 'ArrowRight' ? -1 : 1) : (e.key === 'ArrowRight' ? 1 : -1); currentCardIdx = Math.max(0, Math.min(cards.length - 1, currentCardIdx + dir)); cards[currentCardIdx].classList.add('open'); cards[currentCardIdx].scrollIntoView({ behavior: 'smooth', block: 'center' }); playSound('click'); } }); }
function toggleCard(id) { const card = document.getElementById(id); if (card) { card.classList.toggle('open'); playSound('click'); } }
function toggleHelp() { document.getElementById('helpPanel').classList.toggle('hidden'); playSound('click'); }
function toggleDuaPanel() { document.getElementById('duaPanel').classList.toggle('hidden'); playSound('click'); }
function showToast(msg) { const t = document.getElementById('toast'); const m = document.getElementById('toastMsg'); if (t && m) { m.textContent = msg; t.style.display = 'block'; setTimeout(() => t.style.display = 'none', 2500); } }
function initScrollTop() { const btn = document.getElementById('scrollTop'); window.addEventListener('scroll', () => { if (btn) btn.classList.toggle('visible', window.scrollY > 300); }); }
const AudioCtx = window.AudioContext || window.webkitAudioContext; let audioCtx;
function playSound(type) { try { if (!audioCtx) audioCtx = new AudioCtx(); const osc = audioCtx.createOscillator(); const gain = audioCtx.createGain(); osc.connect(gain); gain.connect(audioCtx.destination); gain.gain.value = 0.06; if (type === 'click') { osc.frequency.value = 800; osc.type = 'sine'; gain.gain.value = 0.04; } else if (type === 'success') { osc.frequency.value = 523; osc.type = 'sine'; } else if (type === 'theme') { osc.frequency.value = 440; osc.type = 'triangle'; gain.gain.value = 0.05; } osc.start(); osc.stop(audioCtx.currentTime + 0.1); } catch(e) {} }
